/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

public class App {

    public static void main(String[] args) {
        SumCalculator calculator = new SumCalculator();
            System.out.println(calculator.sum(3));
    }
}
